#!/bin/zsh

PROJECT_DIRS=$(find -L $@ -maxdepth 1 -type d -not -name '*.playground')
PROJECT_PATH=$(echo $PROJECT_DIRS | fzf --delimiter / --with-nth -1)
PROJECT_NAME=$(basename $PROJECT_PATH)
session_name="$PROJECT_NAME"

if [ -z "$PROJECT_PATH" ]; then
    exit 1
fi

cd $PROJECT_PATH

not_in_tmux() {
  [ -z "$TMUX" ]
}

session_exists() {
  tmux has-session -t "=$session_name"
}

create_detached_session() {
  (TMUX='' tmux new-session -Ad -s "$session_name")
}

create_if_needed_and_attach() {
  if not_in_tmux; then
    tmux new-session -As "$session_name"
  else
    if ! session_exists; then
      create_detached_session
    fi
    tmux switch-client -t "$session_name"
  fi
}

create_if_needed_and_attach
