#!/bin/bash

# Purpose: Print a markdown table with one blank row given a comma separated list of headings

# Display help if first argument is '?'
if [[ "$1" = "?" ]]; then
 SCRIPT_NAME=$(basename "$0")
 echo "Purpose: Create a markdown table with one blank row given a comma separated list of headings."
 echo "Usage: $SCRIPT_NAME heading_1, heading_2, heading_n"
 exit 0
fi

table=$(
 # Get comma separated headings from arguments
 IFS=',' read -ra headings <<<"$@"

 # Table boundary character
 delim="|"

 # Print Headings
 for item in "${headings[@]}"; do
  # Print heading preceded with the delimiter
  # And remove any leading or trailing spaces
  item=$(echo "${item}" | sed 's/^ *//g; s/ *$//g')
  printf "%s" "${delim}${item}"
 done
 echo $delim

 # Print spacer line
 for item in "${headings[@]}"; do
  printf $delim
 done
 echo $delim

 # Print empty first row
 for item in "${headings[@]}"; do
  printf $delim
 done
 echo $delim
)

# Format the table
SCRIPT_FULL_PATH=$(dirname "$0")
"${SCRIPT_FULL_PATH}/TableFormat" <<<"${table}"
