#!/bin/zsh

# Purpose: Add new columns to a markdown table
# Usage: Provide headings separated by ','

# Get column names
COLUMN_NAMES=$(echo $@ | sed 's/,/\|/g')

# Add new headings to first row, and print rest
AWK_CMD="
FNR == 1 { print \$0\"${COLUMN_NAMES}|\"};
FNR >= 2 { print }
"

# Format the table
SCRIPT_FULL_PATH=$(dirname "$0")
awk "${AWK_CMD}" </dev/stdin |
 "${SCRIPT_FULL_PATH}/TableFormat"
