export PATH="$PATH:$HOME/.local/bin"
export PATH="$PATH":"$HOME/.pub-cache/bin"
export PATH="$PATH":"usr/local/go/bin"
export PATH="$PATH":"$HOME/go/bin"
export PATH="/opt/homebrew/opt/util-linux/bin:$PATH"
