#!/usr/bin/env sh

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_shadow                on
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config window_border                off
yabai -m config window_border_width          6
yabai -m config active_window_border_color   0xff775759
yabai -m config normal_window_border_color   0xff555555
yabai -m config insert_feedback_color        0xffd75f5f
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  12
yabai -m config bottom_padding               12
yabai -m config left_padding                 12
yabai -m config right_padding                12
yabai -m config window_gap                   06

# float system preferences. Most of these just diable Yabai form resizing them.
yabai -m rule --add app="^System Preferences$" sticky=on layer=above manage=off
yabai -m rule --add app="^Karabiner-Elements$" sticky=on layer=above manage=off
yabai -m rule --add app="^Karabiner-EventViewer$" sticky=on layer=above manage=off
yabai -m rule --add app="^Finder$" sticky=on layer=above manage=off
yabai -m rule --add app="^Disk Utility$" sticky=on layer=above manage=off
yabai -m rule --add app="^System Information$" sticky=on layer=above manage=off
yabai -m rule --add app="^Code$" manage=off
yabai -m rule --add app="^Calendar$" manage=off layer=above
yabai -m rule --add app="^Notes$" manage=off layer=above


# Space labels 3 desktops per display
# 1 and 4 main => comms + browser
# 2 and 5 dev => dev + tool
# 3 and 6 misc =>  notes + media 
yabai -m space 1 --label "Primary"
yabai -m space 2 --label "Dev"
yabai -m space 5 --label "Tools"
yabai -m space 4 --label "Comms"
yabai -m space 5 --label "Social"
yabai -m space 6 --label "Float"
yabai -m space 7 --label "Secondary"


# Tools
yabai -m rule --add app="Alacritty"             space=2
yabai -m rule --add app="Code"                  space=2
yabai -m rule --add app="Postman"               space=5
yabai -m rule --add app="Fork"                  space=5
yabai -m rule --add app="Simulator"             space=5

#Primary
yabai -m rule --add app="Chrome"                space=1

# Media
yabai -m rule --add app="VLC"                   space=6
yabai -m rule --add app="Spotify"               space=6

# Social & Communication 
yabai -m rule --add app="Discord"               space=4
yabai -m rule --add app="WhatsApp"              space=4
yabai -m rule --add app="Slack"                 space=4
yabai -m rule --add app="Microsoft Outlook"     space=4
yabai -m rule --add app="Messages"              space=4

echo "yabai configuration loaded.."
