vim.cmd [[ autocmd BufEnter *.dart :lua vim.api.nvim_buf_set_option(0, "commentstring", "// %s") ]]
vim.cmd [[ autocmd CursorHold * :lua vim.lsp.diagnostic.show_line_diagnostics() ]]
vim.cmd [[ autocmd BufWritePre *.dart lua vim.lsp.buf.formatting() ]]
-- vim.cmd [[ autocmd BufEnter,FileType *.dart set colorcolumn=81]]
vim.cmd [[ autocmd UIEnter * :hi Normal guibg=NONE ctermbg=NONE ]]
